export const productsValidation = async (packageId, products) => {
    try {
        // get package 
    } catch (error) {
        console.log(error);
        return { success: false, errorStack: `some internal error at products validation, please try after sometime` }
    }
}